/**
 * Build item data from the picture table.
 *
 *   client/assets/items/items.csv   the table (edit in any spreadsheet app)
 *   client/assets/items/*.png       the pictures (transparent backgrounds)
 *     -> shared/minigames/items.generated.js
 *
 * For every row it reads the PNG, works out the item's height from the
 * picture's proportions, and runs the solid/transparent pixel scan
 * (shared/minigames/pixelMask.js) to get its collision shape.
 *
 * Runs automatically before `npm run build`, `npm run dev` and `npm test`.
 * Run it yourself with `npm run items` after changing pictures or the table.
 */
import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { PNG } from 'pngjs';
import { CELL, buildMask, encodeMask, solidCells } from '../shared/minigames/pixelMask.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const dir = join(root, 'client/assets/items');
const KNOWN_USES = new Set(['fridge', 'yours', 'microwave', 'recycle', 'toilet', 'stinky']);

function parseCsv(text) {
  const lines = text.split(/\r?\n/).map((l) => l.trim()).filter((l) => l && !l.startsWith('#'));
  const header = lines.shift().split(',').map((h) => h.trim().toLowerCase());
  return lines.map((line, i) => {
    const cells = line.split(',').map((c) => c.trim());
    const row = Object.fromEntries(header.map((h, k) => [h, cells[k] ?? '']));
    row.line = i + 2;
    return row;
  });
}

const problems = [];
const items = [];
for (const row of parseCsv(readFileSync(join(dir, 'items.csv'), 'utf8'))) {
  const where = `items.csv line ${row.line} (${row.id || 'no id'})`;
  if (!/^[a-z0-9_]+$/.test(row.id)) { problems.push(`${where}: id must be lowercase letters, digits or _`); continue; }
  const file = join(dir, row.file);
  if (!existsSync(file)) { problems.push(`${where}: can't find ${row.file}`); continue; }
  const width = Number(row.width);
  if (!(width >= CELL)) { problems.push(`${where}: width must be a number (world units)`); continue; }
  const uses = row.uses.split(/\s+/).filter(Boolean);
  const unknown = uses.filter((u) => !KNOWN_USES.has(u));
  if (unknown.length) problems.push(`${where}: unknown use "${unknown.join(' ')}" (known: ${[...KNOWN_USES].join(', ')})`);

  const png = PNG.sync.read(readFileSync(file));
  const height = Math.round((width * png.height) / png.width);
  const cols = Math.ceil(width / CELL);
  const rows = Math.ceil(height / CELL);
  const mask = buildMask(png.data, png.width, png.height, cols, rows);
  const solid = solidCells(mask, cols, rows).length;
  if (!solid) { problems.push(`${where}: the picture is completely transparent`); continue; }
  items.push({ id: row.id, name: row.name || row.id, file: row.file, w: width, h: height, cols, rows, uses, mask: encodeMask(mask, cols, rows) });
}

if (problems.length) {
  console.error(`Item table problems:\n  ${problems.join('\n  ')}`);
  process.exit(1);
}

const out = `// GENERATED by scripts/build-items.mjs from client/assets/items/items.csv.
// Don't edit by hand: change the table or the pictures and run \`npm run items\`.
export const ITEM_CELL = ${CELL};
export const ITEMS = ${JSON.stringify(items, null, 1)};
`;
writeFileSync(join(root, 'shared/minigames/items.generated.js'), out);
console.log(`Built ${items.length} items from items.csv`);
